//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArteEmpresarialPROY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public long idCliente { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string NombreEmpresa { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string RTN { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
