//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArteEmpresarialPROY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.Venta_de_Detalle = new HashSet<Venta_de_Detalle>();
        }
    
        public long idVenta { get; set; }
        public long idCliente { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Totalimpuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_de_Detalle> Venta_de_Detalle { get; set; }
    }
}
